### ISSUE TITLE
NullPointerException when passing no LTL Formula

### ISSUE THREAD

**Issue by tegrity** [hadesrofl/oaltl#12]
When running the program and the user is asked to enter a LTL formula, if you just press enter, the program cancels, throwing the following NullPointerException

> Exception in thread "main" java.lang.NullPointerException
> 	at de.uzl.hsr.oaltl.Run.main(Run.java:34)

**Comment by haka95** [comment]
Fixed in commit 1455e3333347bd1db6e819bc0344bf426237154d
When the user enters an empty formula he is asked again.
